/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CertificateContract } from "./CertificateContract";
export type { EnhancedCertificateContract } from "./EnhancedCertificateContract";
