// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvgmnlkdfqfsdpmmilnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2Z21ubGtkZnFmc2RwbW1pbG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjIyMzgsImV4cCI6MjA3MTg5ODIzOH0.wd6r5a7M9ERjZwm1azvscyG8WGmRkZOchxzT_UzBPis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});