/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CertificateContract {
  export type CertificateStruct = {
    id: BigNumberish;
    recipient: AddressLike;
    name: string;
    course: string;
    institution: string;
    dateIssued: BigNumberish;
    isValid: boolean;
  };

  export type CertificateStructOutput = [
    id: bigint,
    recipient: string,
    name: string,
    course: string,
    institution: string,
    dateIssued: bigint,
    isValid: boolean
  ] & {
    id: bigint;
    recipient: string;
    name: string;
    course: string;
    institution: string;
    dateIssued: bigint;
    isValid: boolean;
  };
}

export interface CertificateContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "certificates"
      | "getCertificate"
      | "getRecipientCertificates"
      | "getTotalCertificates"
      | "issueCertificate"
      | "nextCertificateId"
      | "owner"
      | "recipientCertificates"
      | "revokeCertificate"
      | "transferOwnership"
      | "verifyCertificate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CertificateIssued" | "CertificateRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "certificates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipientCertificates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCertificates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [AddressLike, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCertificateId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recipientCertificates",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipientCertificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCertificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCertificateId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recipientCertificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    certificateId: BigNumberish,
    recipient: AddressLike,
    name: string,
    course: string
  ];
  export type OutputTuple = [
    certificateId: bigint,
    recipient: string,
    name: string,
    course: string
  ];
  export interface OutputObject {
    certificateId: bigint;
    recipient: string;
    name: string;
    course: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [certificateId: BigNumberish];
  export type OutputTuple = [certificateId: bigint];
  export interface OutputObject {
    certificateId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateContract extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateContract;
  waitForDeployment(): Promise<this>;

  interface: CertificateContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certificates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        id: bigint;
        recipient: string;
        name: string;
        course: string;
        institution: string;
        dateIssued: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  getCertificate: TypedContractMethod<
    [_certificateId: BigNumberish],
    [CertificateContract.CertificateStructOutput],
    "view"
  >;

  getRecipientCertificates: TypedContractMethod<
    [_recipient: AddressLike],
    [bigint[]],
    "view"
  >;

  getTotalCertificates: TypedContractMethod<[], [bigint], "view">;

  issueCertificate: TypedContractMethod<
    [
      _recipient: AddressLike,
      _name: string,
      _course: string,
      _institution: string,
      _dateIssued: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  nextCertificateId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recipientCertificates: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  revokeCertificate: TypedContractMethod<
    [_certificateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyCertificate: TypedContractMethod<
    [_certificateId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        id: bigint;
        recipient: string;
        name: string;
        course: string;
        institution: string;
        dateIssued: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [_certificateId: BigNumberish],
    [CertificateContract.CertificateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecipientCertificates"
  ): TypedContractMethod<[_recipient: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTotalCertificates"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [
      _recipient: AddressLike,
      _name: string,
      _course: string,
      _institution: string,
      _dateIssued: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextCertificateId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recipientCertificates"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<[_certificateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<[_certificateId: BigNumberish], [boolean], "view">;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(uint256,address,string,string)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;

    "CertificateRevoked(uint256)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
  };
}
