/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as certificateSol from "./Certificate.sol";
export type { certificateSol };
import type * as certificateV2Sol from "./CertificateV2.sol";
export type { certificateV2Sol };
export type { CertificateContract } from "./CertificateContract";
export type { Counter } from "./Counter";
export * as factories from "./factories";
export type { CertificateContract } from "./Certificate.sol/CertificateContract";
export { CertificateContract__factory } from "./factories/Certificate.sol/CertificateContract__factory";
export { Counter__factory } from "./factories/Counter__factory";
